version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/flowboard

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300

  AfterInstall:
    - location: scripts/install.sh
      timeout: 900

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300